# 服务器配置
server:
  port: 6001
  session-timeout: 30
  tomcat.max-threads: 0
  tomcat.uri-encoding: UTF-8

# spring相关配置
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/wxmall?useUnicode=true&characterEncoding=UTF-8&serverTimezone=Asia/Shanghai&useOldAliasMetadataBehavior=true
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: 123456
    type: com.zaxxer.hikari.HikariDataSource
  #      hikari:
  #        connection-test-query: SELECT 1
  #        maximum-pool-size: 20
  #        minimum-idle: 5
  #        connection-init-sql: SET NAMES utf8mb4
  #        connection-timeout: 30000
  #        auto-commit: true
  #        max-lifetime: 1800000
  jpa:
    show-sql: true
    open-in-view: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5Dialect
        globally_quoted_identifiers: true
        jdbc:
          time_zone: Asia/Shanghai
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB
    rabbitmq:
      addresses: 127.0.0.1:5672
      username: admin
      password: admin
  redis:
    host: 127.0.0.1
    port: 6379
    jedis:
      pool:
        max-active: 50  #连接池最大连接数
        max-idle: 10  # 连接池中的最小空闲连接
        max-wait: 30000    # 连接池最大阻塞等待时间
    #    cluster:
    #      nodes: ${redis.cluster_nodes}
    timeout: 10000  # 连接超时时间
    database: 0   #默认是索引为0的数据库

#graphql:
# servlet:
#  mapping: /graphql
#  enabled: true
#  corsEnabled: true
#tools:
#  schemaLocationPattern: "**/*.graphqls"

logging:
  level:
    com.demo.controller: 'off'